# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'call.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Call(object):
    def setupUi(self, Dialog_Call):
        Dialog_Call.setObjectName("Dialog_Call")
        Dialog_Call.resize(557, 328)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Call)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_Call)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbn_1 = QtWidgets.QRadioButton(Dialog_Call)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbn_1.setFont(font)
        self.rbn_1.setObjectName("rbn_1")
        self.horizontalLayout.addWidget(self.rbn_1)
        self.rbn_2 = QtWidgets.QRadioButton(Dialog_Call)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbn_2.setFont(font)
        self.rbn_2.setObjectName("rbn_2")
        self.horizontalLayout.addWidget(self.rbn_2)
        self.rbn_3 = QtWidgets.QRadioButton(Dialog_Call)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbn_3.setFont(font)
        self.rbn_3.setObjectName("rbn_3")
        self.horizontalLayout.addWidget(self.rbn_3)
        self.pushButton = QtWidgets.QPushButton(Dialog_Call)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(Dialog_Call)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(31)
        self.tableWidget.verticalHeader().setMinimumSectionSize(22)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Call)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_Call)
        self.buttonBox.accepted.connect(Dialog_Call.accept)
        self.buttonBox.rejected.connect(Dialog_Call.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Call)

    def retranslateUi(self, Dialog_Call):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Call.setWindowTitle(_translate("Dialog_Call", "Калькулятор пчеловода"))
        self.label.setText(_translate("Dialog_Call", "Расчет сахарного сиропа"))
        self.rbn_1.setText(_translate("Dialog_Call", "1х1"))
        self.rbn_2.setText(_translate("Dialog_Call", "1,5х1"))
        self.rbn_3.setText(_translate("Dialog_Call", "2Х1"))
        self.pushButton.setText(_translate("Dialog_Call", "Расчитать"))
