# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'karta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Karta(object):
    def setupUi(self, Dialog_Karta):
        Dialog_Karta.setObjectName("Dialog_Karta")
        Dialog_Karta.resize(826, 541)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Karta)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_Karta)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Karta)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_Karta)
        self.buttonBox.accepted.connect(Dialog_Karta.accept)
        self.buttonBox.rejected.connect(Dialog_Karta.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Karta)

    def retranslateUi(self, Dialog_Karta):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Karta.setWindowTitle(_translate("Dialog_Karta", "Карта пасеки"))
        self.label.setText(_translate("Dialog_Karta", "TextLabel"))
