# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_ulei.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_OpenUlei(object):
    def setupUi(self, Dialog_OpenUlei):
        Dialog_OpenUlei.setObjectName("Dialog_OpenUlei")
        Dialog_OpenUlei.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_OpenUlei)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(Dialog_OpenUlei)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog_OpenUlei)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_OpenUlei)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(Dialog_OpenUlei)
        self.buttonBox.accepted.connect(Dialog_OpenUlei.accept)
        self.buttonBox.rejected.connect(Dialog_OpenUlei.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_OpenUlei)

    def retranslateUi(self, Dialog_OpenUlei):
        _translate = QtCore.QCoreApplication.translate
        Dialog_OpenUlei.setWindowTitle(_translate("Dialog_OpenUlei", "Открыть улей"))
        self.label.setText(_translate("Dialog_OpenUlei", "Выберите улей"))
