# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Plem(object):
    def setupUi(self, Dialog_Plem):
        Dialog_Plem.setObjectName("Dialog_Plem")
        Dialog_Plem.resize(527, 383)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Plem)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Dialog_Plem)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Plem)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_Plem)
        self.buttonBox.accepted.connect(Dialog_Plem.accept)
        self.buttonBox.rejected.connect(Dialog_Plem.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Plem)

    def retranslateUi(self, Dialog_Plem):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Plem.setWindowTitle(_translate("Dialog_Plem", "Селекционная работа"))
